# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8766092c3f8a820431ce61fbbe95d3329b8ff344f2c7d896c2bc73662256610680030157ca63c129f5a05c160264dc6664339db5f067198396cba502cbf776

test:
  secret_key_base: b4b9b6b1170e27821201bac2fed336481c23dd86512a46d1e2afa80eae4bcd3b8df6f2fc05bc6cf944261a6602faa04bde56e00029024f05052c0859eb3f6896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
